s = set()
n =(input("Enter the number of elements: "))
s.add(int(n))
n =(input("Enter the number of elements: "))
s.add(int(n))
n =(input("Enter the number of elements: "))
s.add(int(n))
n =(input("Enter the number of elements: "))
s.add(int(n))
n =(input("Enter the number of elements: "))
s.add(int(n))
n =(input("Enter the number of elements: "))
s.add(int(n))
n =(input("Enter the number of elements: "))
s.add(int(n))
n =(input("Enter the number of elements: "))
s.add(int(n))
print("The set is:", s)